### ISSUE TITLE
[FEATURE] Meta CMS 主页样式和文字调整

### ISSUE THREAD

**Issue by Linklinkguan** [Meta-Network/meta-cms-frontend#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
## 菜单栏

- [x] 将LOGO替换为六边形，名称替换为 “Meta Space CMS“
- [x] 让左侧的菜单栏文字保持左侧对齐（二级菜单的文字和一级菜单文字也要对齐）
- [x] 左侧菜单栏的间隔调整：快捷访问区和菜单区保持最大间隔，菜单和菜单之间保持第二大间隔，二级菜单之间保持最小的间隔
- [x] 将“我的 Meta Space”替换为下面的卡片样式，展示ICON、标题、域名，点击可以跳转到站点
    - [x] 替换“我的 Meta Space” 的图标为六边形（参照 Meta Network），鼠标指向该卡片的时候将ICON替换为 此图标
![image](https://user-images.githubusercontent.com/10827774/134324823-bb4a439b-4c5e-4768-b3cf-cb5e0a046083.png)
![image](https://user-images.githubusercontent.com/10827774/134324855-3471d22f-b719-4aef-9a05-c1a12fe95ab0.png)

- [x] 在“邀请码”的右侧增加 剩余可用数量的显示
- [x] 在“已发布”的右侧增加 数量的显示
![image](https://user-images.githubusercontent.com/10827774/134324977-f5a815a4-5b36-498a-927e-d43c0fc94396.png)
![image](https://user-images.githubusercontent.com/10827774/134325053-534bce16-3efb-4dcc-89eb-7c72d5abe48d.png)

## 创建 Meta Space 流程文字
- 域名
    - 先为您的 Meta Space 创建一个易于访问的子域名
    - 未来您将可以使用更加个性化的域名配置，包括使用自定义域名
- 信息
    - 定制您的 Meta Space 需要填写一些基础信息
    - 这些信息会公开展示给来访者
- 主题
    - 为您的 Meta Space 挑选一个喜欢的主题
    - 未来您将可以更换或个性化主题配置，包括使用社区开发主题
- 存储
    - 选择一个可信第三方存存储平台以托管您的 Meta Space 配置和内容
    - 我们只会在您授权的情况下帮您创建和修改
    - 未来您将可以更换或个性化存储方案，包括去中心化存储和self-host
    - 请在下方输入 Meta Space 存储仓库的名称（仅用于创建，不影响使用）
- 发布
    - 管理您的 Meta Space 的内容发布方案
    - 未来您将可以手动配置详细的发布方案，甚至可以共享给他人使用以获得回报
    - 此高级功能暂时采用默认配置
    - 我们会根据您选择的存储平台自动提供其对应的发布方式
    - 当前选择的存储服务：**GitHub**
- CDN
    - 管理您的 Meta Space 的 CDN （内容分发网络）方案
    - 未来您可以自由接入第三方的个性化 CDN 服务
    - 此高级功能暂时采用默认配置
    - 为了建站流程简单直接，我们暂时对此配置项应用默认配置。

- 授权说明
    - 授权使用 GitHub 作为 Meta Space 存储仓库（免费）
    - 授权流程：
    - 1. 点击下方按钮前往 GitHub 的授权页面（若无账号则可以注册）
    - 2. 点击授权页面中的绿色按钮（Authorize Meta Network）
【[ICON] Github】

- 返回页面
    - 您已成功授权 Github 作为存储仓储
    - 现在您可以关闭此浏览器页面
 
**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/10827774/134462407-589239fc-365d-40a1-97db-b7fc7fbf82eb.png)

![image](https://user-images.githubusercontent.com/10827774/134463382-8526e3a9-8a5c-49d4-8fc9-83a4b1f2766f.png)

![image](https://user-images.githubusercontent.com/10827774/134328514-a4490e00-ba15-4538-af0d-8497e1428395.png)
